about_us/urls.py
from django.urls import path
from .views import about_us

app_name = 'about_us'

urlpatterns = [
    path('about-us/', about_us, name='about_us'),
]

account/urls.py
from django.urls import path
from .views import Login,Register

app_name = 'account'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
]

article/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, ArticleSearchList, SaveArticleList, add_save_post, remove_save_post

app_name = 'article'

urlpatterns = [
    path('', ArticleList.as_view(), name='article_list'),
    path('articles/', ArticleSearchList.as_view(), name="article_search"),
    path('saved-articles/', SaveArticleList.as_view(), name="article_save"),
    path('add-save-article/<int:pk>/', add_save_post, name="article_save_add"),
    path('remove-save-article/<int:pk>/', remove_save_post, name="article_save_remove"),
    path('articles/<int:pk>/<slug:slug>/', ArticleDetail.as_view(), name='article_detail'),
]

contact/urls.py
from django.urls import path
from .views import CreateContact

app_name = 'contact'

urlpatterns = [
    path('contact/', CreateContact.as_view(), name='create_contact'),
]

progma/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from account.views import logout_view
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include("article.urls", namespace="article")),
    path('', include('social_django.urls', namespace='social')),
    path('', include('subscribers.urls', namespace='subscribers')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('about_us.urls', namespace='about_us')),
    path('', include('account.urls', namespace='account')),
    path('logout/', logout_view, name='logout'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]

handler404 = 'progma.views.view_404'
handler403 = 'progma.views.view_403'
handler400 = 'progma.views.view_400'
handler500 = 'progma.views.view_500'

if settings.DEBUG:
    # ADD ROOT STATIC FILES
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # ADD MEDIA STATIC FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Shared/Footer.html
<footer class="footer text-center py-2 theme-bg-dark">
    <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
    <div class="sahel text-center">انتشار مقالات با ذکر منبع بلامانع است | <a href="{% url 'article:article_list' %}">پروگما</a>
    </div>
</footer>

templates/Shared/Header.html
{% load static %}
{% url 'article:article_list' as article_list %}
{% url 'article:article_save' as article_save %}
<header class="header text-center">
    <h1 class="blog-name pt-lg-4 mb-0 sahel-bold"><a href="{% url 'article:article_list' %}">برنامه نویسی با پروگما</a>
    </h1>

    <nav class="navbar navbar-expand-lg navbar-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navigation" class="collapse navbar-collapse flex-column">
            <div class="profile-section pt-3 pt-lg-0">
                <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'images/profile.png' %}"
                     alt="image">

                <div class="bio mb-3">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان
                    گرافیک است.<br><a class="text-decoration-none a-m-h" href="#">منو بیشتر بشناس ...</a></div>
                <!--//bio-->
                <ul class="social-list list-inline py-3 mx-auto">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                </ul><!--//social-list-->
                <hr style="margin-top: 20px;margin-bottom: 20px;border: 0;border-top: 1px solid #FFFFFF;">
            </div><!--//profile-section-->

            <ul class="navbar-nav flex-column text-left">
                <li class="nav-item {% if request.path == article_list %}active{% endif %}">
                    <a class="nav-link" href="{% url 'article:article_list' %}"><i
                            class="fas fa-newspaper fa-fw ml-2"></i>مقالات</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item {% if request.path == article_save %}active{% endif %}">
                        <a class="nav-link" href="{{ article_save }}"><i class="fas fa-bookmark fa-fw ml-2"></i>ذخیره
                            شده</a>
                    </li>{% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="about.html"><i class="fas fa-user fa-fw ml-2"></i>درباره من</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html"><i class="fas fa-phone fa-fw ml-2"></i>تماس با من</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="


                                {% if request.path == article_save %}{% url 'logout' %}{% else %}{% url 'logout' %}?next={{ request.path }}{% endif %}"
                        >

                            <i class="fas fa-sign-out-alt fa-fw ml-2"></i>خروج</a>
                    </li>
                {% endif %}
            </ul>

            <div class="my-2 my-md-2">
                {% if not user.is_authenticated %}
                    <a class="mb-3 btn btn-warning text-dark" style="height: auto"
                       href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">ورود
                        با
                        گوگل <i class="fab fa-google"></i></a>
                {% else %}
                    <a class="mb-3 btn btn-warning text-dark" style="height: auto">خوش
                        آمدی {% if user.get_full_name %}{{ user.get_full_name }}{% else %}
                            {{ user.username }}{% endif %}</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

templates/Shared/Sidebar.html
{% url 'article:article_list' as article_list %}
{% url 'article:article_search' as article_search %}
{% url 'article:article_save' as article_save %}
{% url 'about_us:about_us' as about_us %}
{% url 'contact:create_contact' as contact %}
<header class="header text-center">
    <h1 class="blog-name pt-lg-4 mb-0 sahel-bold"><a href="{% url 'article:article_list' %}">برنامه نویسی با پروگما</a>
    </h1>

    <nav class="navbar navbar-expand-lg navbar-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navigation" class="collapse navbar-collapse flex-column">
            <div class="profile-section pt-3 pt-lg-0">
                                <img class="profile-image mb-3 rounded-circle mx-auto" src="{{ settings.site_logo.url }}"
                                     alt="پروگما">
                <div class="bio mb-3">{{ settings.short_about_us }}</div>
                <div class="m-0">
                    <a class="text-decoration-none a-m-h" href="{{ about_us }}">پروگما رو بیشتر بشناس ...</a>
                </div>
                <!--//bio-->
                <ul class="social-list list-inline py-3 mx-auto">
                    <li class="list-inline-item"><a target="_blank" href="https://twitter.com/{{ settings.twitter }}"><i
                            class="fab fa-twitter fa-fw"></i></a></li>
                    <li class="list-inline-item"><a target="_blank" href="https://t.me/{{ settings.telegram }}"><i
                            class="fab fa-telegram"></i></a>
                    </li>
                    <li class="list-inline-item"><a target="_blank" href="https://github.com/{{ settings.github }}"><i
                            class="fab fa-github fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item"><a target="_blank"
                                                    href="https://www.instagram.com/{{ settings.instagram }}"><i
                            class="fab fa-instagram fa-fw"></i></a></li>
                    <li class="list-inline-item"><a target="_blank" href="https://youtube.com/{{ settings.youtube }}"><i
                            class="fab fa-youtube fa-fw"></i></a></li>
                </ul><!--//social-list-->
                <hr style="margin-top: 20px;margin-bottom: 20px;border: 0;border-top: 1px solid #FFFFFF;">
            </div><!--//profile-section-->

            <ul class="navbar-nav flex-column text-left">
                <li class="nav-item {% if request.path == article_search %}active{% endif %}">
                    <a class="nav-link" href="{{ article_search }}"><i
                            class="fas fa-newspaper fa-fw ml-2"></i>مقالات</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item {% if request.path == article_save %}active{% endif %}">
                        <a class="nav-link" href="{{ article_save }}"><i class="fas fa-bookmark fa-fw ml-2"></i>ذخیره
                            شده</a>
                    </li>{% endif %}
                <li class="nav-item {% if request.path == about_us %}active{% endif %}">
                    <a class="nav-link" href="{{ about_us }}"><i class="fas fa-user fa-fw ml-2"></i>درباره من</a>
                </li>
                <li class="nav-item {% if request.path == contact %}active{% endif %}">
                    <a class="nav-link" href="{{ contact }}"><i class="fas fa-phone fa-fw ml-2"></i>تماس با من</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="











                                {% if request.path == article_save %}{% url 'logout' %}{% else %}{% url 'logout' %}?next={{ request.path }}{% endif %}">
                            <i class="fas fa-sign-out-alt fa-fw ml-2"></i>خروج</a>
                    </li>
                {% endif %}
            </ul>

            <div class="my-2 my-md-2">
                {% if not user.is_authenticated %}
                    <div class="col-md-12 text-center">
                        <button class="btn btn-warning text-dark mb-3">
                            <a class="text-dark"
                               href="{% url 'account:login' %}?next={{ request.get_full_path }}">ورود</a>
                            / <a class="text-dark" href="{% url 'account:register' %}">ثبت نام</a>
                        </button>
                    </div>

                    <div class="col-md-12">
                        <button class="mb-3 btn btn-warning text-dark">
                            <a class="text-dark"
                               href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.get_full_path }}"
                               style="height: auto">ورود ب گوگل <i class="fab fa-google"></i></a>
                        </button>
                    </div>

                {% else %}
                    <a class="mb-3 btn btn-warning text-dark" style="height: auto">خوش
                        آمدی {% if user.get_full_name %}{{ user.get_full_name }}{% else %}
                            {{ user.username }}{% endif %}</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

templates/Shared/__FooterReferences.html
{% load static %}
<script src="{% static 'plugins/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'plugins/popper.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

templates/Shared/__HeaderReferences.html
{% load static %}
<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="پروگما برای برنامه نویسان">
<meta name="author" content="علیرضا جواب ور">
<link rel="shortcut icon" href="{{ settings.site_icon.url }}">

<!-- FontAwesome JS-->
<script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"
        integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7"
        crossorigin="anonymous"></script>

<!-- Theme CSS -->
<link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">
<link rel="stylesheet" href="{% static 'css/rtl.css' %}">

templates/Shared/base.html
{% load render_partial %}
{% url 'subscribers:subscribe' as subscribe %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <title>پروگما | {% block title %}{% endblock %}</title>
    {% render_partial 'progma.views.site_header_references' %}
    {% block add_header_reference %}{% endblock %}
</head>
<body>
{% render_partial 'progma.views.site_sidebar' %}
<div class="main-wrapper">
    {% include 'Shared/messages.html' %}
    {% block content %}{% endblock %}
    {% if not request.path == subscribe %}
        <div style="font-size: 1.1rem;background-color: #ffc107 !important"
             class="col-12 intro sahel-bold text-center p-1">برای
            دریافت آخرین مقالات از طریق
            ایمیل <a style="color: red" href="{% url 'subscribers:subscribe' %}">کلیک</a> کن !
        </div>
    {% endif %}
    {% include 'Shared/Footer.html' %}
</div><!--//main-wrapper-->
<!-- Javascript -->
{% include 'Shared/__FooterReferences.html' %}
{% block add_footer_reference %}{% endblock %}
</body>
</html>

templates/Shared/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="text-center {% if msg.tags %}alert alert-{{ msg.tags }}{% endif %}">
            {{ msg }}
        </div>
    {% endfor %}
{% endif %}