account/urls.py
from django.urls import path
from .views import Login,Register

app_name = 'account'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
]

article/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, ArticleSearchList, SaveArticleList, add_save_post, remove_save_post

app_name = 'article'

urlpatterns = [
    path('', ArticleList.as_view(), name='article_list'),
    path('articles/', ArticleSearchList.as_view(), name="article_search"),
    path('saved-articles/', SaveArticleList.as_view(), name="article_save"),
    path('add-save-article/<int:pk>/', add_save_post, name="article_save_add"),
    path('remove-save-article/<int:pk>/', remove_save_post, name="article_save_remove"),
    path('articles/<int:pk>/<slug:slug>/', ArticleDetail.as_view(), name='article_detail'),
]

progma/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from account.views import logout_view
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include("article.urls", namespace="article")),
    path('', include('social_django.urls', namespace='social')),
    path('', include('subscribers.urls', namespace='subscribers')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('about_us.urls', namespace='about_us')),
    path('', include('account.urls', namespace='account')),
    path('logout/', logout_view, name='logout'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/login/', RedirectView.as_view(url='/')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]

handler404 = 'progma.views.view_404'
handler403 = 'progma.views.view_403'
handler400 = 'progma.views.view_400'
handler500 = 'progma.views.view_500'

if settings.DEBUG:
    # ADD ROOT STATIC FILES
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # ADD MEDIA STATIC FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.utils import timezone
from account.models import User
import os
import random
from django.db.models import Q
from ckeditor_uploader.fields import RichTextUploadingField
from extensions.utils import jalali_converter
from django.db.models.signals import post_save
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from subscribers.models import Subscribe
from django.shortcuts import reverse


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_list_path(instance, filename):
    random_num = random.randint(1, 989999999)
    name, ext = get_filename_ext(filename)
    final_name = f"{random_num}-{instance.slug}{ext}"
    return f"articles/image-list/{final_name}"


def upload_image_path(instance, filename):
    random_num = random.randint(1, 989999999)
    name, ext = get_filename_ext(filename)
    final_name = f"{random_num}-{instance.slug}{ext}"
    return f"articles/image/{final_name}"


class ArticleManager(models.Manager):
    def get_publish_article(self):
        return self.get_queryset().filter(status='p')

    def search(self, query):
        lookup = (Q(title__icontains=query) |
                  Q(description__icontains=query) |
                  Q(tags__title__icontains=query)
                  )
        return self.get_queryset().filter(lookup, status='p').distinct()


class ArticleTagManager(models.Manager):
    def get_active_tag(self):
        return self.get_queryset().filter(active=True)


class CommentManager(models.Manager):
    def get_active_comment(self):
        return self.get_queryset().filter(active=True, parent__isnull=True)

    def get_active_reply(self):
        return self.get_queryset().filter(active=True, parent__isnull=False)


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آی پی آدرس")
    time = models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت")

    class Meta:
        verbose_name = "آی پی آدرس"
        verbose_name_plural = "آی پی آدرس ها"

    def __str__(self):
        return self.ip_address

    def jtime(self):
        return jalali_converter(self.time)

    jtime.short_description = "زمان ثبت"


class ArticleTag(models.Model):
    title = models.CharField(max_length=400, verbose_name="عنوان برچسب")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="آدرس برچسب")
    active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ArticleTagManager()

    class Meta:
        verbose_name = "برچسب"
        verbose_name_plural = "برچسب"
        ordering = ['-created']

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     if not self.active:
    #         for article in self.article_tags.get_publish_article():
    #             article.status = 'd'
    #             article.save()
    #     super(ArticleTag, self).save(*args, **kwargs)


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),  # draft
        ('p', "منتشر شده"),  # publish
    )

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles',
                               verbose_name="نویسنده")
    title = models.CharField(max_length=400, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=200, verbose_name="آدرس مقاله")
    description = RichTextUploadingField(verbose_name="محتوا")
    image_list = models.ImageField(upload_to=upload_image_list_path, verbose_name="تصویر 135*135 مقاله")
    image = models.ImageField(upload_to=upload_image_path, verbose_name="تصویر مقاله")
    tags = models.ManyToManyField(ArticleTag, blank=True, related_name='article_tags', verbose_name='تگ ها / برچسب ها')
    hits = models.ManyToManyField(IPAddress, blank=True, related_name="article_hits", verbose_name="بازید")
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d', verbose_name="وضعیت")
    send_email = models.BooleanField(default=True, verbose_name='ارسال ایمیل')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ArticleManager()

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def author_str(self):
        return str(self.author)

    def get_url(self):
        return reverse('article:article_detail', kwargs={'pk': self.pk, 'slug': self.slug})

    author_str.short_description = 'نویسنده'

    def tags_str(self):
        return " - ".join([tag.title for tag in self.tags.get_active_tag()])

    tags_str.short_description = 'تگ ها / برچسب ها'


class SaveArticle(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='save_article', verbose_name='کاربر')
    articles = models.ManyToManyField(Article, related_name='save_article', verbose_name='مقالات', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "مقاله ذخیره شده"
        verbose_name_plural = "مقالات ذخیره شده"
        ordering = ['-created']

    def __str__(self):
        return str(self.user)

    def get_articles(self):
        return self.articles


class Comment(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='user_comment',
                             verbose_name='کاربر')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_comment', verbose_name='مقاله')
    content = models.TextField(verbose_name='نظر')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='replies',
                               verbose_name='زیر نظر')
    active = models.BooleanField(default=False, verbose_name="فعال / غیرفعال")
    created = models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت")
    updated = models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش")

    objects = CommentManager()

    class Meta:
        verbose_name = "دیدگاه مقالات"
        verbose_name_plural = "دیدگاه های مقالات"
        ordering = ['-created']

    def __str__(self):
        return f'{str(self.article)} - {str(self.user)} - {self.content[0:70]}'

    def jtime(self):
        return jalali_converter(self.created)

    jtime.short_description = "زمان ثبت"


def send_email_users(sender, instance, created, **kwargs):
    emails = []
    for sub in Subscribe.objects.get_active_subscribe():
        emails += sub.email.split()
    content = instance
    get_url = instance.get_url()
    msg_html = render_to_string('email/new-article-send-email.html', {'content': content, 'get_url': get_url})
    if instance.send_email == True and instance.status == 'p':
        subject = f'پروگما | مقاله جدید | {instance.title}'
        message = msg_html
        email_from = settings.EMAIL_HOST_USER
        recipient_list = emails
        send_mail(subject, message, email_from, recipient_list, html_message=msg_html)
        article = Article.objects.get(id=instance.id)
        article.send_email = False
        article.save()


def create_save_article(sender, **kwargs):
    if kwargs['created']:
        save_article = SaveArticle(user=kwargs['instance'])
        save_article.save()


post_save.connect(send_email_users, sender=Article)
post_save.connect(create_save_article, sender=User)

article/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

article/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.generic import ListView, DetailView
from .models import Article, SaveArticle, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.views.generic.edit import FormMixin


class ArticleList(ListView):
    queryset = Article.objects.get_publish_article()
    template_name = 'article/article-list.html'
    paginate_by = 10


class ArticleSearchList(ListView):
    def get_queryset(self):
        request = self.request
        query = request.GET.get("s")
        if query is not None:
            return Article.objects.search(query)
        return Article.objects.get_publish_article()

    template_name = 'article/article-list.html'
    paginate_by = 10


class SaveArticleList(LoginRequiredMixin, ListView):
    def get_queryset(self):
        save_article = SaveArticle.objects.get(user=self.request.user)
        articles = save_article.articles.get_publish_article().order_by('-article_savearticle_articles.id')
        return articles

    template_name = 'article/save-article-list.html'
    paginate_by = 10


class ArticleDetail(FormMixin, DetailView):
    # queryset = Article.objects.get_publish_article()
    template_name = 'article/article-detail.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('article:article_detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})

    def get_object(self):
        article = get_object_or_404(Article.objects.get_publish_article(),
                                    slug=self.kwargs.get('slug'),
                                    pk=self.kwargs.get('pk'),
                                    )
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            messages.success(request, 'دیدگاه تو با موفقیت ثبت شد ، منتظر تایید باش', 'success')
            return self.form_valid(form)
        else:
            messages.error(request, 'یه مشکلی هست دوباره سعی کن !', 'danger')
            return self.form_invalid(form)

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            self.obj = form.save(commit=False)
            self.obj.article = self.object
            self.obj.user = self.request.user
            self.obj.status = False
            try:
                # id integer e.g. 15
                self.obj.parent_id = int(self.request.POST.get('parent_id'))
            except:
                self.obj.parent_id = None

            form.save()
        return super(ArticleDetail, self).form_valid(form)


@login_required()
def add_save_post(request, **kwargs):
    if request.method == 'POST':
        article_pk = kwargs['pk']
        save_article = SaveArticle.objects.get(user=request.user)
        article = Article.objects.get(pk=article_pk)
        if article is None or article.status == 'd':
            raise Http404()
        if article in save_article.articles.get_publish_article():
            messages.error(request, 'این مقاله رو قبلا ذخیره کردی', 'danger')
            if request.GET.get("next"):
                return redirect(request.GET.get("next"))
            else:
                return HttpResponseRedirect(reverse('article:article_list'))
        save_article.articles.add(article)
        messages.success(request, 'مقاله با موفقیت ذخیره شد', 'success')
        save_article.save()
        if request.GET.get("next"):
            return redirect(request.GET.get("next"))
        else:
            return HttpResponseRedirect(reverse('article:article_list'))
    else:
        raise Http404('404 error')


@login_required()
def remove_save_post(request, **kwargs):
    if request.method == 'POST':
        article_pk = kwargs['pk']
        save_article = SaveArticle.objects.get(user=request.user)
        article = Article.objects.get(pk=article_pk)
        if article is None or article.status == 'd':
            raise Http404()
        if article not in save_article.articles.get_publish_article():
            messages.error(request, 'اصا این مقاله رو ذخیره نکردی !', 'danger')
            if request.GET.get("next"):
                return redirect(request.GET.get("next"))
            else:
                return HttpResponseRedirect(reverse('article:article_list'))
        save_article.articles.remove(article)
        messages.success(request, 'مقاله با موفقیت از ذخیره ها حذف شد', 'success')
        save_article.save()
        if request.GET.get("next"):
            return redirect(request.GET.get("next"))
        else:
            return HttpResponseRedirect(reverse('article:article_list'))
    else:
        raise Http404('404 error')

templates/article/article-detail.html
{% extends 'Shared/base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% load ratings %}

{% block add_header_reference %}
    <link rel="stylesheet" href="{% static 'comments/comments.css' %}">
    <!-- Star Ratings -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
{% endblock %}
{% block title %}مقاله {{ object.title }}{% endblock %}
{% block content %}
    <article class="blog-post px-3 py-5 p-md-5">
        <div class="container">
            <header class="blog-post-header">
                <h2 class="title mb-2">{{ object.title }}</h2>
                <div class="meta mb-3">
                    <span class="date">{{ object.publish|naturaltime }}</span>
                    <span class="comment">نویسنده : <a>{% if object.author.get_full_name %}
                        {{ object.author.get_full_name }}{% else %}{{ object.author.username }}{% endif %}</a></span>
                    <span class="time">{{ object.hits.count }} بازدید</span>
                    <span class="comment"><a>{{ object.article_comment.get_active_comment.count }} دیدگاه</a></span>
                </div>
            </header>
            <div class="blog-post-body">
                <figure class="blog-banner">
                    <a href="{% url 'article:article_detail' object.pk object.slug %}"><img class="img-fluid"
                                                                                            src="{{ object.image.url }}"
                                                                                            alt="{{ object.title }}"></a>
                </figure>
                <div class="text-center mr-5">
                    <div style="margin-left: 10rem;margin-bottom: -1.3rem">
                        امتیاز :
                    </div>
                    {% ratings object %}
                </div>
                <div class="mt-1">{{ object.description|safe }}</div>
                {% if user.is_authenticated %}
                    <div class="article-tag text-center">
                        {% if object not in user.save_article.articles.get_publish_article %}
                            <form method="post"
                                  action="{% url 'article:article_save_add' object.pk %}?next={{ request.get_full_path }}">
                                {% csrf_token %}
                                <button style="padding: 0" class="btn text-danger" type="submit"><i
                                        style="font-size: 1.4rem;"
                                        class="fas fa-save"></i>
                                    <span class="mr-1">ذخیره مقاله</span></button>

                            </form>
                        {% else %}
                            <form method="post"
                                  action="{% url 'article:article_save_remove' object.pk %}?next={{ request.get_full_path }}">
                                {% csrf_token %}
                                <button style="padding: 0" class="btn text-danger" type="submit"><i
                                        style="font-size: 1.4rem;"
                                        class="fas fa-save"></i>
                                    <span class="mr-1">حذف از ذخیره شده ها</span></button>

                            </form>
                        {% endif %}

                    </div>
                {% endif %}
                <div class="text-justify article-tag">
                    <span>برچسب ها :</span> {% for tag in object.tags.get_active_tag %}
                    <a href="/articles/?s={{ tag.title }}">{{ tag.title }}</a>{% endfor %}
                </div>
                <div class="my-4" style="border-bottom: 1px solid gray;"></div>
                <div id="article-comment" class="blog-comments-section">
                    <div class="row">
                        <div class="col-md-12"><h3 style="color: #3B7EEB;margin-bottom:30px !important;">دیدگاه ها
                            ({{ object.article_comment.get_active_comment.count }})</h3>
                        </div>
                        <div class="col-md-12 mb-4 text-center">
                            {% if user.is_authenticated %}
                                <div class="media-body">

                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {% render_field form.content class="form-control rounded-lg border" rows="4" placeholder="نوشتن دیدگاه ..." %}
                                        </div>
                                        <button type="submit" class="btn btn-sm btn-primary">ارسال</button>
                                    </form>
                                </div>
                            {% else %}
                                <p class="alert alert-danger text-center">برای ثبت دیدگاه <a
                                        href="{% url 'account:login' %}?next={{ request.path }}">ورود</a>
                                    کنید</p>
                            {% endif %}
                        </div>
                        <div class="col-md-12">
                            <div class="blog-comment">

                                <ul class="comments">
                                    {% for comment in object.article_comment.get_active_comment %}
                                        <li class="clearfix">
                                            <div class="post-comments">
                                                <p class="meta">{{ comment.created|naturaltime }} <a
                                                        class="mr-1 text-primary">
                                                    {% if comment.user.get_full_name %}
                                                        {{ comment.user.get_full_name }}{% else %}
                                                        {{ comment.user.username }}{% endif %}</a>
                                                    <i class="mr-2" class="pull-right"><a class=""
                                                                                          data-toggle="collapse"
                                                                                          href="#collapseExample{{ comment.id }}"
                                                                                          role="button"
                                                                                          aria-expanded="false"
                                                                                          aria-controls="collapseExample"><small>پاسخ
                                                        ({{ comment.replies.get_active_reply.count }})</small></a></i>
                                                </p>
                                                <p class="text-justify">
                                                    {{ comment.content }}
                                                </p>
                                            </div>
                                            <div class="collapse" id="collapseExample{{ comment.id }}">
                                                {% if user.is_authenticated %}
                                                    <div class="media-body mb-3 text-center">
                                                        <form method="post">
                                                            {% csrf_token %}

                                                            <div class="form-group">
                                                                {% render_field form.content class="form-control rounded-lg border" rows="1" placeholder="نوشتن پاسخ ..." %}

                                                            </div>
                                                            <!-- Hidden input for parent comment.id -->
                                                            <input type="hidden" name="parent_id"
                                                                   value="{{ comment.id }}">
                                                            <button type="submit" class="btn btn-sm btn-primary">ارسال
                                                            </button>
                                                        </form>
                                                    </div>
                                                {% else %}
                                                    <p class="alert alert-danger text-center">برای ثبت پاسخ <a
                                                            href="{% url 'account:login' %}?next={{ request.path }}">ورود</a>
                                                        کنید</p>
                                                {% endif %}
                                                {% for reply in comment.replies.get_active_reply %}
                                                    <ul class="comments reply">
                                                        <li class="clearfix">
                                                            <div class="post-comments reply-background">
                                                                <p class="meta">{{ reply.created|naturaltime }} <a
                                                                        class="mr-1" href="#">
                                                                    {% if reply.user.get_full_name %}
                                                                        {{ reply.user.get_full_name }}{% else %}
                                                                        {{ reply.user.username }}{% endif %}</a>
                                                                </p>
                                                                <p>
                                                                    {{ reply.content }}
                                                                </p>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                {% endfor %}
                                            </div>
                                        </li>
                                    {% empty %}
                                        {% if user.is_authenticated %}
                                            <p class="alert alert-warning text-center">هنوز نظری ثبت نشده ، تو اولین نظر
                                                رو
                                                ثبت کن</p>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                    </div>


                </div>
            </div>

        </div>

    </article>

{% endblock %}
{% block add_footer_reference %}
    <!-- Star Ratings -->
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
{% endblock %}